[book]
title = "German Occidentalist"
description = "Digitalisat numer√≥s del bulletine del German Occidental-Federation."
authors = ["Deutscher Occidental-Sprachbund"]
language = "ie"
multilingual = false
src = "src"

[output.html]
no-section-label = true
default-theme = "rust"
preferred-dark-theme = "rust"

[output.html.search]
use-boolean-and = true

[build]
build-dir = "docs"
